import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await fs.mkdir('tests/screenshots/v2',{recursive:true});
await page.goto('http://127.0.0.1:4173');await page.waitForSelector('#world[data-environment="cinematic"]',{timeout:20000});await page.waitForTimeout(1400);
await page.screenshot({path:'tests/screenshots/v2/desktop.png'});
const frameTimes=await page.evaluate(()=>new Promise(resolve=>{const samples=[];let previous=performance.now();function frame(now){samples.push(now-previous);previous=now;if(samples.length<90)requestAnimationFrame(frame);else resolve(samples.slice(5).sort((a,b)=>a-b));}requestAnimationFrame(frame);}));
console.log('Desktop frame timing, ms:',{median:frameTimes[Math.floor(frameTimes.length*.5)],p95:frameTimes[Math.floor(frameTimes.length*.95)]});
await fs.writeFile('tests/screenshots/v2/timings.json',JSON.stringify({viewport:'1440 × 1000',browser:'Chrome headless',samples:frameTimes.length,medianMs:frameTimes[Math.floor(frameTimes.length*.5)],p95Ms:frameTimes[Math.floor(frameTimes.length*.95)]},null,2));
console.log('Environment:',await page.locator('#world').getAttribute('data-environment'),'errors:',errors);
await page.getByRole('button',{name:'03 — GramGramTV',exact:true}).click();await page.waitForTimeout(3000);await page.screenshot({path:'tests/screenshots/v2/tv.png'});
await page.getByRole('button',{name:'05 — MyApp Hub',exact:true}).click();await page.waitForTimeout(2800);await page.screenshot({path:'tests/screenshots/v2/mac.png'});
await page.setViewportSize({width:768,height:1024});await page.getByRole('button',{name:'06 — Pausa',exact:true}).click();await page.waitForTimeout(2800);await page.screenshot({path:'tests/screenshots/v2/ipad.png'});
await page.setViewportSize({width:390,height:844});await page.getByRole('link',{name:'ProdX0x, début du voyage'}).click();await page.waitForTimeout(3000);await page.screenshot({path:'tests/screenshots/v2/mobile.png'});
await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:4173/?quality=basic');await page.waitForTimeout(1000);await page.screenshot({path:'tests/screenshots/v2/fallback.png'});
console.log('Fallback:',await page.locator('#world').getAttribute('data-environment'),'errors:',errors);
await browser.close();if(errors.length)process.exitCode=1;
